### PR TITLE
feat: standardize make extract_translations

### PR DESCRIPTION
**Pull request by shadinaif**
feat: standardize make extract_translations

This PR prepares the repository to comply with [openedx-translations](https://github.com/openedx/openedx-translations) by doing the following:

* Move all local translations to `conf/locale` and convert `translations` into a symbolic link to `conf/locale`. The reason behind that is to comply with [openedx-translations](https://github.com/openedx/openedx-translations) mechanism that requires translation files to be in `conf/locale` directory. This fix will avoid the need to modify `find` commands [here](https://github.com/openedx/openedx-translations/blob/b85fafbac85e7c57fd8f11d75b15f10338ac1d7e/.github/workflows/extract-translation-source-files.yml#L85)
* Add the translation command `make extract_translations` to build a file named `django.po` instead of `text.po`. And create a symbolic link from `text.po` to `django.po`. This is because [openedx-translations](https://github.com/openedx/openedx-translations) requires `django.po` as the name of the file. And it must be a valid file (not a link) because it uses `git add` [here](https://github.com/openedx/openedx-translations/blob/b85fafbac85e7c57fd8f11d75b15f10338ac1d7e/.github/workflows/extract-translation-source-files.yml#L100)

- [x] Tested on devstack palm to ensure that everything renders fine
- [x] Tested on devstack palm to ensure that local translation still works

References
----------

This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Check the links above for full information about the overall project.

Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
 - Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` files will be committed into the repos.
 - Add standardized `make extract_translations` in all repositories
 - Push user-facing messages strings into [openedx/openedx-translations](https://github.com/openedx/openedx-translations/).
 - Integrate root repositories with [openedx/openedx-atlas](https://github.com/openedx/openedx-atlas/) to pull translations on build/deploy time

Breaking Changes
----------------

One of the primary goals of the project is to **avoid breaking changes**. If you noticed any suspicious code, please raise your concern. But before that, please know the strategy we're following to avoid breaking changes

**For XBlocks:**
 - The standard translation path must be `conf/locale`. Therefore, we are creating a link from `conf/locale` to `translations` so Atlas can find the path without disrupting the current way of having translations locally within the XBlocks
 - [openedx-translations](https://github.com/openedx/openedx-translations) will have a related PR that adds the XBlock to the pipeline. This will not affect the current way of managing/updating translations
 - At the end of the project, a clear change log will be added and all translations will be handled by Atlas. Thus, the local translation will be removed from the repo within the version bump
 - A notification for the community will be published to ensure that everyone knows why translations directories are removed from all repos

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by shadinaif** [comment]
Hi @iloveagent57 , I'm starting a PR for [FC-0012 Project](https://openedx.atlassian.net/l/cp/XGS0iCcQ). Can you please explain why there are two translation directories? one for [consent and integrate apps](https://github.com/openedx/edx-enterprise/tree/master/enterprise/conf), and another for [enterprise app](https://github.com/openedx/edx-enterprise/tree/master/enterprise/locale). Shouldn't we combine them all in a single translation directory?

cc: @OmarIthawi, @brian-smith-tcril

**Comment by iloveagent57** [comment]
@shadinaif sorry for the delay in responding, I'll try to find someone with historical context on this.  I don't personally know the answer.

**Comment by iloveagent57** [comment]
@saleem-latif had some context here that he shared with me:
PR: https://github.com/openedx/edx-enterprise/pull/1037

> I think the directory conf/locale was created alongside the edx-enterprise app. Initially, it only had markings for strings in the en directory, no translations were added. With ENT-3529 we wanted to add translations for Spanish (specifically for data sharing page. More information in the comments of  ENT-3529 on this.)
> The reason I added a new directory at this point is because Django provided following 3 ways to enable translations
> 1. The directories listed in LOCALE_PATHS have the highest precedence, with the ones appearing first having higher precedence than the ones appearing later.
> 2. Then, it looks for and uses if it exists a locale directory in each of the installed apps listed in INSTALLED_APPS. The ones appearing first have higher precedence than the ones appearing later.
> 3. Finally, the Django-provided base translation in [django/conf/locale](https://github.com/django/django/blob/main/django/conf/locale) is used as a fallback.
> ref: https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#how-django-discovers-translations
> 
> For external Django apps like edx-enterprise , IMO the best approach is to use 2nd approach, which led to the creation of locale directory.
> I should have remove conf/locale directory at this point, but I do not remember if I forgot to do so or if there was some other reason. I think we can remove this directory now if removing it does not cause any issues.

**Review by OmarIthawi — APPROVED** [review]
testing my new permissions, not a real review

**Review by OmarIthawi — APPROVED** [review]
testing my new permissions, not a real review

**Comment by shadinaif** [comment]
Thank you @iloveagent57 !

**Comment by mphilbrick211** [comment]
Hi @shadinaif and @OmarIthawi - just checking to see if this PR can be closed?

**Comment by shadinaif** [comment]
Thank you for the follow-up @mphilbrick211 , I'm resting it now to convert it into (Ready for review)

**Comment by mphilbrick211** [comment]
@shadinaif @iloveagent57 looks like tests need to be re-enabled.

**Comment by OmarIthawi** [comment]
@iloveagent57 would you mind enabling tests one more time? It should be ready to merge.

**Review by brian-smith-tcril — APPROVED** [review]
This looks great! Thank you!

**Comment by brian-smith-tcril** [comment]
@iloveagent57 I'd like to merge this. You are listed as "please inform" on the spreadsheet. If there's any reason I should hold off please let me know, otherwise I'll plan on merging this tomorrow morning.

**Review by OmarIthawi — APPROVED** [review]
I've tested it locally and it looks good to me. Thanks @shadinaif!

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-enterprise&entry.867055334=https://github.com/openedx/edx-enterprise/pull/1751&entry.1484655318=https://github.com/shadinaif&entry.752974735=2023-05-09+09:03&entry.1917517419=2023-11-17+16:21&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
