### PR TITLE
chore: Update to the new version of paragon in the new scope.

### PR DESCRIPTION
**Pull request by feanil**
Part of https://github.com/openedx/axim-engineering/issues/23

This replaces the `@edx/paragon` packag to point to the `paragon` package at
the `openedx` scope(`@openedx/paragon`). Imports have been updated to use the
same locations in the new package.

### CODE REVIEW

**Comment by feanil** [comment]
@openedx/enterprise-titans this is a fairly major version bump in the paragon version.  Let me know if there are any specific tests that I should perform above the basic CI to verify this changes.

**Comment by adamstankiewicz** [comment]
> @openedx/enterprise-titans this is a fairly major version bump in the paragon version. Let me know if there are any specific tests that I should perform above the basic CI to verify this changes.

@feanil Luckily no React components from Paragon are used within this repo. That said, there are some features like the https://courses.edx.org/enterprise/select/active page that rely on some of the class names from Paragon/Bootstrap (e.g., `.form-control`) on the default Django UI elements. For example, this "Select an organization" page relies on the core Paragon styles and the aforementioned `.form-control` class name:

image

The changes made in [this PR](https://github.com/openedx/edx-enterprise/pull/1074) that first introduced `@edx/paragon` into this repo (in favor of `@edx/edx-bootstrap`) should have largely taken care of the majority of issues that faced the repo related to Paragon; the core class names like `.form-control`, typography, etc. from Bootstrap have not changed since the v12 version currently installed.

Given this, these changes otherwise feels fairly low risk to me, but some flows like the above one should likely be verified on stage/prod with a quick run through to ensure no style regressions. I'm not sure how familiar you are with setting up / testing Enterprise flows, so I'd be happy to help you with a quick manual run through of some common Enterprise user flows that depend on `edx-enterprise` like the one above once this lands on stage to ensure no style regressions.

**Comment by feanil** [comment]
@adamstankiewicz I don't have access to your stage systems to verify these changes there.  Is it possible to set these up in a pre-stage environment like devstack or tutor?

**Comment by feanil** [comment]
@adamstankiewicz any update on this, do you have docs on how to setup the relevant views in a dev environment or can you do the verification on stage for this?

**Comment by feanil** [comment]
@adamstankiewicz I was able to get this running locally and verify that there weren't any paragon CSS related errors on the enterprise pages:

### Before upgrade

enterprise-before-paragon-upgrade

### After Upgrade

enterprise-after-paragon-upgrade


I think this change is ready to go.

**Review by arbrandes — APPROVED** [review]
Approving based on @adamstankiewicz's comments and @feanil's testing.

**Review by adamstankiewicz — APPROVED** [review]
@feanil thanks for verifying with the screenshot.

If this intends to be released to PyPi as a new version such that it can be upgraded in edx-platform, the PR should include a [CHANGELOG entry](https://github.com/openedx/edx-enterprise/blob/cc4a8100fb2d030d745194a9951467283e696109/CHANGELOG.rst#L4) and an update to the version specified in [the `init.py` file](https://github.com/openedx/edx-enterprise/blob/cc4a8100fb2d030d745194a9951467283e696109/enterprise/__init__.py#L5). 

@feanil @arbrandes Do you plan on getting these changes upgraded into `edx-platform` or are you planning on just merging the PR?

**Comment by feanil** [comment]
@adamstankiewicz yes, I'll bump the version, add the changelog entry and get this landed in edx-platform.

**Pull request merged**
