### PR TITLE
Fix github url strings (org edx -> openedx)

### PR DESCRIPTION
**Pull request by sarina**
## This PR was autogenerated

This pr replaces the old GitHub organization, github.com/edx, with the new GitHub organization, github.com/openedx.

Tagging @openedx/tcril-engineering for review, but others are welcome to provide review.

Ref: https://github.com/openedx/tcril-engineering/issues/42

### CODE REVIEW

**Comment by sarina** [comment]
I was awaiting review on this PR. I can have tCRIL do the review if your team does not have time.

**Comment by johnnagro** [comment]
@sarina  i can review, approve, and merge this HOWEVER the branch currently has marge conflicts. can you resolve them?

**Comment by feanil** [comment]
@johnnagro this is rebased and ready to review.

**Comment by sarina** [comment]
I was waiting for the tests to finish running before letting John know 😛

**Comment by sarina** [comment]
passed!

**Review by johnnagro — APPROVED** [review]

**Pull request merged**
