### PR TITLE
build: enable CI for pull requests

### PR DESCRIPTION
**Pull request by 0x29a**
This change enables CI checks for PRs targeted against branches other than `master`.

This is useful for stacked PRs, as it allows to run checks for all dependent PRs.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @0x29a! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: we've been applying this change manually to our branches since Nutmeg
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a

**Comment by Agrendalath** [comment]
@e0d, would you be able to help with merging this?

**Comment by e0d** [comment]
@georgebabey any reason not to merge this?

**Comment by mphilbrick211** [comment]
> @georgebabey any reason not to merge this?

Hi @georgebabey - bumping this!

**Comment by 0x29a** [comment]
@georgebabey, @mphilbrick211, just checking: if the change if fine, can we possibly merge this? Here is [an example](https://github.com/open-craft/edx-enterprise/pull/14) of a chained pull request where this fix would be helpful. You can see that tests aren't being run for it.

**Comment by mphilbrick211** [comment]
> @georgebabey, @mphilbrick211, just checking: if the change if fine, can we possibly merge this? Here is [an example](https://github.com/open-craft/edx-enterprise/pull/14) of a chained pull request where this fix would be helpful. You can see that tests aren't being run for it.

Hi @0x29a - I'm looking into getting this reviewed for you.

**Comment by georgebabey** [comment]
Apologies for the delay, happy to get this merged but it does need a rebase now.

**Review by georgebabey — APPROVED** [review]

**Comment by bradenmacdonald** [comment]
@georgebabey Could you please hit merge here?

**Comment by e0d** [comment]
@bradenmacdonald I noticed the branch is out of date, can you update?

**Comment by bradenmacdonald** [comment]
@e0d Sure, I pressed the update button. That's weird you couldn't, because I know GitHub has functionality to allow maintainers to update PRs even from private forks. I've used it myself as a maintainer on other projects. Maybe there's a setting we need to turn on for this repo?

**Comment by itsjeyd** [comment]
@tecoholic @0x29a Is this PR still needed? And if so, could you please rebase it?

Since @georgebabey [approved the changes](https://github.com/openedx/edx-enterprise/pull/1978#pullrequestreview-1974622287) earlier, I'm assuming we can merge them once the build is green.

CC @mphilbrick211

**Comment by itsjeyd** [comment]
That was quick, thanks @georgebabey and @0x29a 👍

**Comment by Cup0fCoffee** [comment]
@0x29a @Agrendalath Does this need to be backported to Sumac branch of our fork? I would assume, no, but just wanted to check.

**Comment by 0x29a** [comment]
@Cup0fCoffee, we'll certainly have to cherry-pick or do this change in our Sumac branch of our fork - as without this we can't run the pipeline for our fork.

**Pull request merged**
