### PR TITLE
Added channel_name for api call logs records

### PR DESCRIPTION
**Pull request by MueezKhan246**
Description:
Added channel_name for making it easier to delete api call logs records.

JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-8020

### CODE REVIEW

**Review by justEhmadSaeed — APPROVED** [review]
lgtm

**Review by sameenfatima78 — COMMENTED** [review]
we shouldn't hardcode the name. try using constants instead

**Comment by MueezKhan246** [comment]
> we shouldn't hardcode the name. try using constants instead
@sameen i was searching if the names were defined in a dicts or enums but could not find it.
just replaced it with `self.enterprise_configuration.channel_code()` shared by @hamzawaleed01.

**Review by hamzawaleed01 — APPROVED** [review]

**Review by sameenfatima78 — COMMENTED** [review]
looks all good!

**Pull request merged**
